### PR TITLE
Adding insecure option to skip certificate validation

### PR DESCRIPTION
**Pull request by Avielyo10**
We have an expired certificate which we don't have access to change, we want to have the ability to count on our internal certificate without validating it, this option makes it happen.

### CODE REVIEW

**Comment by Avielyo10** [comment]
Sorry about formatting the code, it's a habit, I hope we can leave it

**Comment by ikedam** [comment]
Actually, I don’t think it’s a good idea to support outdated certificates.
You also need to set up Jenkins instances to ignore certificates (though I’m not sure how you can do that).

How about to use a self-signed certificate and distribute its CA certificate instead? UpdateSites Manager plugin supports that use case.
https://plugins.jenkins.io/update-sites-manager

**Comment by Avielyo10** [comment]
@ikedam  I believe that this option can help me and my team to achieve our goal, this is set by default to false so the users who use it need to activate this option which is hidden anyway. I believe it adds more flexibility to this project letting users decide whether they want to use an insecure option or not (by default).

We are building Jenkins from source with this certificate so no need to set-up Jenkins further.[That's how we did it:)]

**Comment by ikedam** [comment]
I won’t plan to have this fork support such a private branch.
Please have your own fork just like you have your private Jenkins binary.

Using outdated certificates are not desirable usage of certificates and I don’t add an option to encourage such usage.

**Comment by Avielyo10** [comment]
Ok.

**Pull request closed without merging**
